// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCol: typeof import('element-plus/es')['ElCol']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElDivider: typeof import('element-plus/es')['ElDivider']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElImage: typeof import('element-plus/es')['ElImage']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
  const ElProgress: typeof import('element-plus/es')['ElProgress']
  const ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
  const ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
  const ElRow: typeof import('element-plus/es')['ElRow']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
  const ElSlider: typeof import('element-plus/es')['ElSlider']
  const ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElUpload: typeof import('element-plus/es')['ElUpload']
}
export {}
